### ISSUE TITLE
Embedded Checkout

### ISSUE THREAD

**Issue by magicspon** [jorgemasta/commercext#1]
Heyo, 

I hope you don't mind me raising an issue here.

I'm trying to work out how to use the embedded checkout.  I've just taken a clone of this repo.

The checkout is coming up as empty.  Are you experiencing the same?

![image](https://user-images.githubusercontent.com/3268717/108739742-d5264d00-752c-11eb-9210-c2e844d60c8d.png)

**Comment by jorgemasta** [comment]
Yes, it is **not** functional at the moment. This is just for testing purposes.

The problem I have is that the checkout can only be embedded in the same domain (or subdomain) where we have the store and that makes it very complex to test it properly.

**Comment by magicspon** [comment]
Thanks for getting back to me.

I've followed the tutorial here:
https://developer.bigcommerce.com/api-docs/storefronts/embedded-checkout/embedded-checkout-tutorial#faq
still no luck

I've used your SSO example, which means I can now manage my users with craftcms, rather than bc, so thanks for that.
